<h1>Privacy Policy </h1>

Begmyrat Mammedov built the Ynamly Sowda app as a Free app. This SERVICE is provided by Begmyrat Mammedov at no cost and is intended for use as is.

This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.

If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The permission that I request is used for providing and improving the Service. I will use the CALL_PHONE permission to make calling system easier for users to order

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Anneliğe Hazırlanıyorum - Gebelik ve Doğum unless otherwise defined in this Privacy Policy.

<h2>Information Collection and Use</h2>

The app does use third party services that may collect information used to identify you.

Link to privacy policy of third party service providers used by the app

Google Play Services
Retrofit

I may employ third-party companies and individuals due to the following reasons:

To facilitate our Service;
To provide the Service on our behalf;
To perform Service-related services; or

<h2>Security</h2>

In the app, there is no personal information that we collect. So, there is no data to secure

<h2>Children’s Privacy</h2>

These Services is developed for everyone and there is not any restriction.

<h3>Changes to This Privacy Policy</h3>

I may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on this page.

This policy is effective as of 2021-01-20

<h2>Contact Us</h2>

If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at info@anneligehazirlaniyorum.com.

This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator
